app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', ['as'=> 'logout', 'uses' => 'Auth\AuthController@getLogout']);

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::get('/', function () {
    return redirect()->route('jobs.index');
});

get('jobs/complete', ['as' => 'jobs.complete', 'uses' => 'JobController@completed']);
post('jobs/restore', ['as' => 'jobs.restore', 'uses' => 'JobController@restore']);
get('jobs/print/{data}', ['as' => 'jobs.print', 'uses' => 'JobController@printImages']);

Route::resource("jobs","JobController", ['except' => 'show']);

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Job extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function Jobs()
    {
        return $this->hasMany(Job::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

abstract class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/JobController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Barryvdh\DomPDF\Facade as PDF;

use App\Job;
use App\User;
use Illuminate\Http\Request;

class JobController extends Controller {
    /**
     * JobController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{

        if(auth()->user()->name == 'Gaz' || auth()->user()->name == 'Robert Dunne')
        {
            $jobs = Job::with('user')->orderBy('id', 'desc')->get();
        } else {
            $jobs = Job::with('user')->where('user_id', auth()->user()->id)->orderBy('id', 'desc')->get();
        }

		return view('jobs.index', compact('jobs'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        if(auth()->user()->name == 'Gaz' || auth()->user()->name == 'Robert Dunne')
        {
            $users = User::where('name', '!=', 'Robert Dunne')->where('name', '!=', 'Gaz')->get(['id', 'name']);
        } else {
            $users = null;
        }

		return view('jobs.create', compact('users'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$job = new Job();

		$job->desc = $request->input("desc");
        $job->location = $request->input("location");
		$job->priority = $request->input("priority");

        if(auth()->user()->name == 'Gaz')
        {
            $job->user_id = $request->input("user");
        } else {
            $job->user_id = auth()->user()->id;
        }

		$job->save();

		return redirect()->route('jobs.index')->with('message', 'Job has been created.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$job = Job::findOrFail($id);

		return view('jobs.show', compact('job'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$job = Job::findOrFail($id);

		return view('jobs.edit', compact('job'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$job = Job::findOrFail($id);

		$job->desc = $request->input("desc");
        $job->location = $request->input("location");
        $job->priority = $request->input("priority");

		$job->save();

		return redirect()->route('jobs.index')->with('message', 'Job updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$job = Job::findOrFail($id);
		$job->delete();

		return redirect()->route('jobs.index')->with('message', 'Job is marked as Complete.');
	}


    /**
     * Show page for completed Jobs
     *
     * @return Response
     */
    public function completed()
    {
        if(auth()->user()->name == 'Gaz' || auth()->user()->name == 'Robert Dunne')
        {
            $jobs = Job::with('user')->onlyTrashed()->orderBy('id', 'desc')->get();
        } else {
            $jobs = Job::with('user')->onlyTrashed()->where('user_id', auth()->user()->id)->orderBy('id', 'desc')->get();
        }

        return view('jobs.completed', compact('jobs'));
    }

    public function restore($id)
    {
        $job = findOrFail($id);
        $job->restore();

        return redirect()->route('jobs.complete')->with('message', 'Job has been Un-Completed');
    }

	public function printImages($data)
	{
		$data = explode('_', $data);
		$data = ['data' => $data];
		foreach($data as $id)
		{
			$job = Job::findorFail($id);
			$jobs['jobs'] = $job;
		}
		$pdf = PDF::loadView('jobs.pdf', $jobs);
		return $pdf->stream('details.pdf');
	}
}

resources/views/error.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <p>There were some problems with your input.</p>
        <ul>
            @foreach ($errors->all() as $error)
                <li><i class="glyphicon glyphicon-remove"></i> {{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/jobs/completed.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Completed Jobs
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($jobs->count())
                <table class="table table-condensed table-striped" id="myTable">
                    <thead>
                    <tr>
                        <th>NURSERY</th>
                        <th>DESC</th>
                        <th>LOCATION</th>
                        <th>Priority</th>
                        <th class="text-right">OPTIONS</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach($jobs as $job)
                        <tr>
                            <td>{{$job->user->name}}</td>
                            <td>{{$job->desc}}</td>
                            <td>{{$job->location}}</td>
                            <td>{{$job->priority}}</td>
                            <td class="text-right">
                                <form action="{{ route('jobs.restore', $job->id) }}" method="POST" style="display: inline;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <button type="submit" class="btn btn-xs btn-warning"><i class="glyphicon glyphicon-ok"></i> Un-Complete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/jobs/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Jobs / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('jobs.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('desc')) has-error @endif">
                       <label for="desc-field">Desc</label>
                    <input type="text" id="desc-field" name="desc" class="form-control" value="{{ old("desc") }}"/>
                       @if($errors->has("desc"))
                        <span class="help-block">{{ $errors->first("desc") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('location')) has-error @endif">
                       <label for="location-field">Location</label>
                    <input type="text" id="location-field" name="location" class="form-control" value="{{ old("location") }}"/>
                       @if($errors->has("location"))
                        <span class="help-block">{{ $errors->first("location") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('priority')) has-error @endif">
                        <label for="priority-field">Priority</label>
                        <select name="priority" id="priority-field" class="form-control">
                            <option value="Low">Low</option>
                            <option value="Normal">Normal</option>
                            <option value="High">High</option>
                        </select>
                        @if($errors->has("location"))
                            <span class="help-block">{{ $errors->first("location") }}</span>
                        @endif
                    </div>
                    @if(auth()->user()->name == 'Gaz' || auth()->user()->name == 'Robert Dunne')
                        <div class="form-group">
                            <label for="nursery-field">Nursery</label>
                            <select name="user" id="nursery-field" class="form-control">
                                @foreach($users as $user)
                                    <option value="{{$user->id}}">{{$user->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    @endif
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('jobs.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/jobs/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Jobs / Edit #{{$job->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('jobs.update', $job->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('desc')) has-error @endif">
                       <label for="desc-field">Desc</label>
                    <input type="text" id="desc-field" name="desc" class="form-control" value="{{ $job->desc }}"/>
                       @if($errors->has("desc"))
                        <span class="help-block">{{ $errors->first("desc") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('location')) has-error @endif">
                       <label for="location-field">Location</label>
                    <input type="text" id="location-field" name="location" class="form-control" value="{{ $job->location }}"/>
                       @if($errors->has("location"))
                        <span class="help-block">{{ $errors->first("location") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('priority')) has-error @endif">
                        <label for="priority-field">Priority</label>
                        <select name="priority" id="priority-field" class="form-control">
                            <option value="Low">Low</option>
                            <option value="Normal">Normal</option>
                            <option value="High">High</option>
                        </select>
                        @if($errors->has("location"))
                            <span class="help-block">{{ $errors->first("location") }}</span>
                        @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('jobs.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/jobs/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Jobs
            <a class="btn btn-success pull-right" href="{{ route('jobs.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($jobs->count())
                <table class="table table-condensed table-striped table-responsive" id="myTable">
                    <thead>
                        <tr>
                            <th><a href="#" id="selectAll"><i class="fa fa-plus-circle"></i></a></th>
                            <th>NURSERY</th>
                            <th>DESC</th>
                            <th>LOCATION</th>
                            <th>Priority</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($jobs as $job)
                            <tr>
                                <td><input type="checkbox" name="print" value="{{$job->id}}"></td>
                                <td>{{$job->user->name}}</td>
                                <td>{{$job->desc}}</td>
                                <td>{{$job->location}}</td>
                                <td>{{$job->priority}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-warning" href="{{ route('jobs.edit', $job->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('jobs.destroy', $job->id) }}" method="POST" style="display: inline;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-ok"></i> Complete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

@section('script')
    <script>
        $(document).ready(function() {
            $('#selectAll').click(function() {
                $('input[name=print]').attr('checked', true);
            });
        });
        $('#Print').click(function() {
            var data = {};
            var dataStrings = [];

            $('input[type="checkbox"]').each(function() {
                if (this.checked) {
                    if (data[this.name] === undefined) data[this.name] = [];
                    data[this.name].push(this.value);
                }
            });

            $.each(data, function(key, value)
            {
                dataStrings.push(value.join('_'));
            });

            var result = dataStrings.join('&');

            window.location.href = "jobs/print/" + result;
        });
    </script>
@endsection

resources/views/jobs/pdf.blade.php
<html>
    <head>
        <style>
            tr {
                padding-bottom: 2em;
            }
        </style>
    </head>
    <body>
        <div class="table-responsive table-hover">
            <table class="table table-striped">
                <thead class="thead-inverse">
                <tr>
                    <th>Nursery</th>
                    <th>Description</th>
                    <th>Location</th>
                    <th>Priority</th>
                </tr>
                </thead>
                <tbody>
                @foreach($jobs as $job)
                    <tr>
                        <td>{{$job->user->name}}</td>
                        <td>{{$job->desc}}</td>
                        <td>{{$job->location}}</td>
                        <td>{{$job->priority}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </body>
</html>

resources/views/jobs/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Jobs / Show #{{$job->id}}</h1>
        <form action="{{ route('jobs.destroy', $job->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('jobs.edit', $job->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="desc">DESC</label>
                     <p class="form-control-static">{{$job->desc}}</p>
                </div>
                    <div class="form-group">
                     <label for="location">LOCATION</label>
                     <p class="form-control-static">{{$job->location}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('jobs.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Maintenance Portal</title>

    <!-- Data tables CSS -->
    <!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/bs/jqc-1.11.3,dt-1.10.10/datatables.min.css"/>-->

    <!-- Bootstrap core CSS -->
    <link href="{{asset('css/app.css')}}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link href="starter-template.css" rel="stylesheet"> -->


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{route('jobs.index')}}">Maintenance Portal</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="{{request()->is('jobs') ? 'active' : ''}}"><a href="{{route('jobs.index')}}">Home</a></li>
                    @if(auth()->check())
                        <li class="{{request()->is('jobs/complete') ? 'active' : ''}}"><a href="{{route('jobs.complete')}}">Completed Jobs</a></li>
                        <li><a href="#" id="Print">Print Selected</a></li>
                    @endif
                </ul>
                @if(auth()->check())
                <ul class="nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{auth()->user()->name}} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{route('logout')}}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
                @endif
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        @yield('header')
        <hr>
        @yield('content')
    </div><!-- /.container -->

    <script type="text/javascript" src="{{asset('js/app.js')}}"></script>
    @yield('script')

</body>
</html>